"""Shell completions for dotfiles-cli."""

from pathlib import Path

from ..utils.console import success, info, header


FISH_COMPLETION = '''# Fish completion for dotfiles
# Auto-generated by dotfiles-cli

# Main commands
complete -c dotfiles -n "__fish_use_subcommand" -a "status" -d "Show overall status"
complete -c dotfiles -n "__fish_use_subcommand" -a "diff" -d "Show pending changes"
complete -c dotfiles -n "__fish_use_subcommand" -a "apply" -d "Apply dotfiles"
complete -c dotfiles -n "__fish_use_subcommand" -a "pull" -d "Pull and apply"
complete -c dotfiles -n "__fish_use_subcommand" -a "push" -d "Commit and push"
complete -c dotfiles -n "__fish_use_subcommand" -a "add" -d "Add file to tracking"
complete -c dotfiles -n "__fish_use_subcommand" -a "remove" -d "Remove from tracking"
complete -c dotfiles -n "__fish_use_subcommand" -a "import" -d "Scan for dotfiles"
complete -c dotfiles -n "__fish_use_subcommand" -a "backup" -d "Backup dotfiles"
complete -c dotfiles -n "__fish_use_subcommand" -a "bootstrap" -d "System setup"
complete -c dotfiles -n "__fish_use_subcommand" -a "doctor" -d "Health check"
complete -c dotfiles -n "__fish_use_subcommand" -a "cd" -d "Print dotfiles path"
complete -c dotfiles -n "__fish_use_subcommand" -a "edit" -d "Open in editor"

# Subcommands
complete -c dotfiles -n "__fish_use_subcommand" -a "secrets" -d "Manage secrets"
complete -c dotfiles -n "__fish_use_subcommand" -a "publish" -d "Publish dotfiles"
complete -c dotfiles -n "__fish_use_subcommand" -a "files" -d "File commands"
complete -c dotfiles -n "__fish_use_subcommand" -a "util" -d "Utilities"
complete -c dotfiles -n "__fish_use_subcommand" -a "git" -d "Git helpers"
complete -c dotfiles -n "__fish_use_subcommand" -a "pkg" -d "Package management"
complete -c dotfiles -n "__fish_use_subcommand" -a "mac" -d "macOS commands"
complete -c dotfiles -n "__fish_use_subcommand" -a "remote" -d "Remote deploy"

# secrets subcommands
complete -c dotfiles -n "__fish_seen_subcommand_from secrets" -a "init" -d "Initialize git-crypt"
complete -c dotfiles -n "__fish_seen_subcommand_from secrets" -a "unlock" -d "Unlock secrets"
complete -c dotfiles -n "__fish_seen_subcommand_from secrets" -a "lock" -d "Lock secrets"
complete -c dotfiles -n "__fish_seen_subcommand_from secrets" -a "status" -d "Show status"
complete -c dotfiles -n "__fish_seen_subcommand_from secrets" -a "list" -d "List encrypted files"

# publish subcommands
complete -c dotfiles -n "__fish_seen_subcommand_from publish" -a "local" -d "Publish to local/public repo"
complete -c dotfiles -n "__fish_seen_subcommand_from publish" -a "gist" -d "Publish bootstrap gist"

# util subcommands
complete -c dotfiles -n "__fish_seen_subcommand_from util" -a "ip" -d "Get public IP"
complete -c dotfiles -n "__fish_seen_subcommand_from util" -a "serve" -d "Start HTTP server"
complete -c dotfiles -n "__fish_seen_subcommand_from util" -a "ssh-init" -d "Setup SSH key"
complete -c dotfiles -n "__fish_seen_subcommand_from util" -a "ghostty" -d "Setup ghostty terminfo"

# git subcommands
complete -c dotfiles -n "__fish_seen_subcommand_from git" -a "init" -d "Create GitHub repo"
complete -c dotfiles -n "__fish_seen_subcommand_from git" -a "quick" -d "Quick commit & push"

# Options
complete -c dotfiles -n "__fish_seen_subcommand_from apply" -s f -l force -d "Force overwrite"
complete -c dotfiles -n "__fish_seen_subcommand_from apply" -s n -l dry-run -d "Dry run"
complete -c dotfiles -n "__fish_seen_subcommand_from push" -s m -l message -d "Commit message"
complete -c dotfiles -n "__fish_seen_subcommand_from diff" -l full -d "Show full diffs"
'''

BASH_COMPLETION = '''# Bash completion for dotfiles
# Auto-generated by dotfiles-cli

_dotfiles() {
    local cur prev commands
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    commands="status diff apply pull push add remove import backup bootstrap doctor cd edit secrets publish files util git pkg mac remote update validate"

    case "${prev}" in
        dotfiles)
            COMPREPLY=($(compgen -W "${commands}" -- "${cur}"))
            return 0
            ;;
        secrets)
            COMPREPLY=($(compgen -W "init unlock lock status list export-key add-pattern" -- "${cur}"))
            return 0
            ;;
        publish)
            COMPREPLY=($(compgen -W "local gist" -- "${cur}"))
            return 0
            ;;
        util)
            COMPREPLY=($(compgen -W "ip serve ssh-init ghostty" -- "${cur}"))
            return 0
            ;;
        git)
            COMPREPLY=($(compgen -W "init quick" -- "${cur}"))
            return 0
            ;;
        backup)
            COMPREPLY=($(compgen -W "create restore list" -- "${cur}"))
            return 0
            ;;
        *)
            ;;
    esac
}

complete -F _dotfiles dotfiles
'''

ZSH_COMPLETION = '''#compdef dotfiles
# Zsh completion for dotfiles
# Auto-generated by dotfiles-cli

_dotfiles() {
    local -a commands
    commands=(
        'status:Show overall status'
        'diff:Show pending changes'
        'apply:Apply dotfiles'
        'pull:Pull and apply'
        'push:Commit and push'
        'add:Add file to tracking'
        'remove:Remove from tracking'
        'import:Scan for dotfiles'
        'backup:Backup dotfiles'
        'bootstrap:System setup'
        'doctor:Health check'
        'cd:Print dotfiles path'
        'edit:Open in editor'
        'secrets:Manage secrets'
        'publish:Publish dotfiles'
        'files:File commands'
        'util:Utilities'
        'git:Git helpers'
        'pkg:Package management'
        'mac:macOS commands'
        'remote:Remote deploy'
        'update:Update CLI'
        'validate:Validate config'
    )

    _describe 'command' commands
}

_dotfiles "$@"
'''


def generate(shell: str = "fish"):
    """Generate shell completions.

    Args:
        shell: Shell type (fish, bash, zsh)
    """
    if shell == "fish":
        print(FISH_COMPLETION)
    elif shell == "bash":
        print(BASH_COMPLETION)
    elif shell == "zsh":
        print(ZSH_COMPLETION)
    else:
        print(f"Unknown shell: {shell}")
        print("Supported: fish, bash, zsh")


def install(shell: str = "fish"):
    """Install shell completions.

    Args:
        shell: Shell type (fish, bash, zsh)
    """
    header(f"Installing {shell} completions")

    if shell == "fish":
        comp_dir = Path.home() / ".config/fish/completions"
        comp_dir.mkdir(parents=True, exist_ok=True)
        comp_file = comp_dir / "dotfiles.fish"
        comp_file.write_text(FISH_COMPLETION)
        success(f"Installed: {comp_file}")

    elif shell == "bash":
        comp_dir = Path.home() / ".local/share/bash-completion/completions"
        comp_dir.mkdir(parents=True, exist_ok=True)
        comp_file = comp_dir / "dotfiles"
        comp_file.write_text(BASH_COMPLETION)
        success(f"Installed: {comp_file}")
        info("Add to ~/.bashrc: source ~/.local/share/bash-completion/completions/dotfiles")

    elif shell == "zsh":
        comp_dir = Path.home() / ".zsh/completions"
        comp_dir.mkdir(parents=True, exist_ok=True)
        comp_file = comp_dir / "_dotfiles"
        comp_file.write_text(ZSH_COMPLETION)
        success(f"Installed: {comp_file}")
        info("Add to ~/.zshrc: fpath=(~/.zsh/completions $fpath)")

    else:
        print(f"Unknown shell: {shell}")
        print("Supported: fish, bash, zsh")
